- id: pyright-pretty
  name: Python type checker [pyright]
  description: Typecheck the current project with the pyright tool
  entry: pyright-pretty
  language: node
  types: [python]
  require_serial: false
  additional_dependencies:
  - "pyright@1.1.394"
  - "typescript@5.3.3"
  - "kleur@4.1.5"
- id: pyright
  name: Python type checker [pyright]
  description: Typecheck the current project with the pyright tool
  entry: pyright
  language: node
  types: [python]
  require_serial: false
  additional_dependencies:
  - "pyright@1.1.394"
  - "typescript@5.3.3"
  - "kleur@4.1.5"
