
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: local
    hooks:
    - id: pyright
      name: Python type checker [pyright]
      description: Typecheck the current project with the pyright tool
      entry: pyright-pretty
      language: node
      types: [python]
      args: [ --debug, --installer=npm, --install-if-missing]
