repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: https://github.com/northisup/pyright-pretty
  rev: main
  hooks:
  - id: pyright-pretty
    args: [--installer=npm, --install-if-missing]
