repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: https://github.com/northisup/pyright-pretty
  rev: main
  hooks:
  - id: pyright
    args:
    - --project=./tests
  - id: pyright-pretty
    args:
    - -- --project=./tests
- repo: local
  hooks:
  - id: mise-build
    name: mise build
    entry: mise run build
    language: system
    pass_filenames: false
    types: [python]
